name: 发布发行版

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - docs/**

env:
  APP_NAME: image-tool

permissions:
  contents: write
  id-token: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.repository }}-${{ github.event.inputs.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
    steps:
      - name: 获取token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 获取用户ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          
      - name: 运行 release-please-action
        id: release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json

  build:
    needs: [release]
    if: needs.release.outputs.releases_created == 'true'
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
            label: windows-x86_64
            build: pnpm build --target x86_64-pc-windows-msvc
          - runner: macos-latest
            target: x86_64-apple-darwin
            label: macos-x86_64
            build: pnpm build --target x86_64-apple-darwin
          - runner: macos-latest
            target: aarch64-apple-darwin
            label: macos-aarch64
            build: pnpm build --target aarch64-apple-darwin
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            label: linux-x86_64
            build: pnpm build --target x86_64-unknown-linux-gnu
          - runner: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            label: linux-aarch64
            build: pnpm build --target aarch64-unknown-linux-gnu
    steps:
      - name: 检出主分支代码
        uses: actions/checkout@v4
        with:
          ref: main

      - name: 设置 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.13.2
          run_install: |
            - args: [--no-frozen-lockfile]

      - name: 安装 Rust 工具链
        uses: dtolnay/rust-toolchain@1.85.0

      - name: 启用 Rust 缓存
        uses: swatinem/rust-cache@v2
        with:
          prefix-key: ${{ env.APP_NAME}}

      - name: 添加目标平台
        run: rustup target add ${{ matrix.platform.target }}
          
      - name: 构建
        shell: bash
        run: |
          ${{ matrix.platform.build }}
          pnpm pkg delete devDependencies
          mkdir -p ${{ runner.temp }}/temp/
          cp -r package.json README.md LICENSE dist ${{ runner.temp }}/temp/
      
      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-${{ matrix.platform.label }}
          path: ${{ runner.temp }}/temp/

  publish-to-github:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 导入构建产物
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: 发布到 GitHub Packages
        id: publish-to-github
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: https://npm.pkg.github.com
          access: public
          provenance: true

  publish-to-npm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 导入构建产物
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: 发布到 NPM
        id: publish-to-npm
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          registry: https://registry.npmjs.org/
          access: public
          provenance: true

